package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ AOTOOLS_VERSION }}"

source:
  url: "https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ AOTOOLS_VERSION }}.tar.gz"

build:
  string: {{ CHANNEL_LABEL }}

requirements:
  host:
    - matplotlib
    - numba
    - numpy {{ NUMPY_VERSION }}.*
    - pip
    - python
    - scipy
  run:
    - matplotlib
    - numba
    - numpy {{ NUMPY_VERSION }}.*
    - python
    - scipy

about:
  home: "https://github.com/aotools/aotools"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "A set of useful functions for Adaptive Optics in Python"
  doc_url: https://aotools.readthedocs.io/en/v1.0.1/
  dev_url: https://github.com/aotools/aotools

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
