package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ AOTOOLS_VERSION_ALT }}"

source:
  url: "https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ AOTOOLS_VERSION }}.tar.gz"

build:
  noarch: python
  string: {{ AOTOOLS_VERSION_ALT }}

requirements:
  build: 
    - python
    - pip

  host:
    - matplotlib
    - numba
    - numpy {{ NUMPY_VERSION_ALT }}.*
    - pip
    - python
    - scipy {{ SCIPY_VERSION_ALT }}

  run:
    - matplotlib
    - numba
    - numpy {{ NUMPY_VERSION_ALT }}.*
    - python
    - scipy {{ SCIPY_VERSION_ALT }}

about:
  home: "https://github.com/aotools/aotools"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "A set of useful functions for Adaptive Optics in Python"
  doc_url: https://aotools.readthedocs.io/en/v1.0.1/
  dev_url: https://github.com/aotools/aotools

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
