package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PFFT_VERSION }}

source:
   git_url: https://github.com/mpip/pfft.git

build:
  string: {{ CHANNEL_LABEL }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - openmpi {{ OPENMPI_VERSION }}.*{{ OPENMPI_BUILD }}
    - fftw {{ FFTW3_VERSION }}.*
    
  host:
   
  run:  
    - openmpi {{ OPENMPI_VERSION }}.*{{ OPENMPI_BUILD }}
    - fftw {{ FFTW3_VERSION }}.*

about:
  home: https://github.com/mpip/pfft
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'PFFT'
  description: |
   PFFT using FFTW3 with MPI extension for frameworks like pinocchio
  doc_url: https://www-user.tu-chemnitz.de/~potts/workgroup/pippig/software.php#pfft
  dev_url: https://github.com/mpip/pfft/

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
