package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PFFT_VERSION_ALT }}

source:
   git_url: https://github.com/mpip/pfft.git
   git_tag: v{{ PFFT_VERSION }}-alpha

build:
  string: {{ PFFT_VERSION_ALT }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - mpich {{ MPICH_VERSION_ALT }}.*
    - fftw {{ FFTW3_VERSION_ALT }}
    
  host:
   
  run:  
    - mpich {{ MPICH_VERSION_ALT }}.*
    - fftw {{ FFTW3_VERSION_ALT }}

about:
  home: https://github.com/mpip/pfft
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'PFFT'
  description: |
   PFFT using FFTW3 with MPI extension for frameworks like pinocchio
  doc_url: https://www-user.tu-chemnitz.de/~potts/workgroup/pippig/software.php#pfft
  dev_url: https://github.com/mpip/pfft/

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
