{% set mpi_impl = environ.get("MPI") %}
{% set mpi_vers = environ.get("MPI_VERSION") %}
{% set mpi_prefix = "mpi_" + mpi_impl %}
{% if mpi_impl == "mpich" or mpi_impl == "openmpi" %}
  # prefer nompi builds via a build number offset
  {% set BUILD_NUMBER = BUILD_NUMBER + 100 %}
  {% set mpi = mpi_impl + " ==" + mpi_vers + ".*" %}
{% else %}
  {% set mpi = "" %}
{% endif %}

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PFFT_VERSION_ALT }}

source:
   git_url: https://github.com/mpip/pfft.git
   git_tag: v{{ PFFT_VERSION }}-alpha

build:
  number: {{ BUILD_NUMBER }}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ BUILD_NUMBER }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - fftw      =={{ FFTW3_VERSION_ALT }}
    - {{ mpi }}
    
  host:
   
  run:  
    - fftw      =={{ FFTW3_VERSION_ALT }}
    - {{ mpi }}

about:
  home: https://github.com/mpip/pfft
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'PFFT'
  description: |
   PFFT using FFTW3 with MPI extension for frameworks like pinocchio
  doc_url: https://www-user.tu-chemnitz.de/~potts/workgroup/pippig/software.php#pfft
  dev_url: https://github.com/mpip/pfft/

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
