{% set mpiImpl = environ.get("MPI") %}
{% set mpiVers = environ.get("MPI_VERSION") %}
{% set mpiBuildStr = "mpi_" + mpiImpl %}
{% if mpiImpl == "mpich" or mpiImpl == "openmpi" %}
  {% set mpiIter = load_str_data([mpiImpl == mpiVers + .*], "json") %}
{% else %}
  {% set mpiIter = load_str_data([], "json") %}
{% endif %}

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PFFT_VERSION_ALT }}

source:
   git_url: https://github.com/mpip/pfft.git
   git_tag: v{{ PFFT_VERSION }}-alpha

build:
  number: {{ BUILD_NUMBER }}
  string: {{% mpiBuildStr + "_" + environ.get("PFFT_VERSION_ALT") %}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - fftw =={{ FFTW3_VERSION_ALT }}
    {% for dep in mpiIter %}
    - {{ dep }}
    {% endfor %}
    
  host:
   
  run:  
    - fftw =={{ FFTW3_VERSION_ALT }}
    {% for dep in mpiIter %}
    - {{ dep }}
    {% endfor %}

about:
  home: https://github.com/mpip/pfft
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'PFFT'
  description: |
   PFFT using FFTW3 with MPI extension for frameworks like pinocchio
  doc_url: https://www-user.tu-chemnitz.de/~potts/workgroup/pippig/software.php#pfft
  dev_url: https://github.com/mpip/pfft/

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
