{% set uNameAndVers = PACKAGE_NAME|replace("-", "_") + "-" + SKA_SDP_DTMDL_VERSION %} # naming convention needs this

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_DTMDL_VERSION_ALT }}

source:
   url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_DTMDL_VERSION }}/{{ uNameAndVers }}.tar.gz

build:
  noarch: python
  number: {{ BUILD_NUMBER }}
  string: {{ SKA_SDP_DTMDL_VERSION_ALT }}
  script_env:
    - INTERNAL_FOLDER_NAME={{ uNameAndVers }}
  
requirements:
  build:
    - python
    - pip 

  host:
    - python
    - pip
    
  run:
    - python
    - pip
    - astroplan         >=0.8,          <0.9
    - astropy           >=5.1,          <6.0 
    - h5py              >=3.7.0
    - numpy             >=1.21, !=1.24.0
    - pandas            >=1.5.0
    - xarray            >=2022.10.0

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels
  license: Apache 2.0
  license_file: {{ uNameAndVers }}/LICENSE
  summary: 'SKA SDP Datamodels'
  description: |
   SKA SDP Datamodels
  doc_url: https://developer.skao.int/projects/ska-sdp-datamodels/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
