{% set mpiImpl = environ.get("MPI") %}
{% set mpiVers = environ.get("MPI_VERSION") %}
{% set mpiBuildStr = "mpi_" + mpiImpl %}
{% if mpiImpl == "mpich" or mpiImpl == "openmpi" %}
  {% set mpiIter = load_str_data([mpiImpl == mpiVers + .*], "json") %}
{% else %}
  {% set mpiIter = load_str_data([], "json") %}
{% endif %}

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ FFTW3_VERSION_ALT }}

source:
   url: https://fftw.org/fftw-{{ FFTW3_VERSION }}.tar.gz 

build:
  string: {{% mpiBuildStr + "_" + environ.get("FFTW3_VERSION_ALT") %}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    {% for dep in mpiIter %}
    - {{ dep }}
    {% endfor %}
    
  host:
    {% for dep in mpiIter %}
    - {{ dep }}
    {% endfor %}
   
  run:
    {% for dep in mpiIter %}
    - {{ dep }}
    {% endfor %}
  

about:
  home: https://github.com/FFTW/fftw3
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'FFTW3 with MPI extension'
  description: |
   FFTW3 libs in double and float compiled with --enable-mpi --enable-openmp --enable-threads --enable-avx --enable-avx2 --enable-shared
  doc_url: http://fftw.org/fftw3_doc/
  dev_url: https://github.com/FFTW/fftw3

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
