{% set mpi_impl = environ.get("MPI") %}
{% set mpi_vers = environ.get("MPI_VERSION") %}
{% set mpi_prefix = "mpi_" + mpi_impl %}
{% if mpi_impl == "mpich" or mpi_impl == "openmpi" %}
  # prefer nompi builds via a build number offset
  {% set BUILD_NUMBER = BUILD_NUMBER + 100 %}
  {% set mpi = mpi_impl + " ==" + mpi_vers + ".*" %}
{% else %}
  {% set mpi = "" %}
{% endif %}

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ FFTW3_VERSION_ALT }}

source:
   url: https://fftw.org/fftw-{{ FFTW3_VERSION }}.tar.gz 

build:
  number: {{ BUILD_NUMBER }}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ BUILD_NUMBER }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - {{ mpi }}
    
  host:
    - {{ mpi }}
   
  run:
    - {{ mpi }}
  

about:
  home: https://github.com/FFTW/fftw3
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'FFTW3 with MPI extension'
  description: |
   FFTW3 libs in double and float compiled with --enable-mpi --enable-openmp --enable-threads --enable-avx --enable-avx2 --enable-shared
  doc_url: http://fftw.org/fftw3_doc/
  dev_url: https://github.com/FFTW/fftw3

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
