package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ EIDOS_VERSION_ALT }}

source:
  git_url: https://github.com/i4Ds/eidos.git
  git_rev: 6537d8487a19442633263b984deec3ac5ff3c575

build:
  noarch: python
  number: {{ BUILD_NUMBER }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ BUILD_NUMBER }}

requirements:
  build:
    - python                  {{ python }}
    - pip
    - numpy                   >=1.21, !=1.24.0
    - scipy                   >=1.10.1
    - astropy
    - future

  host:
    - python                  {{ python }}
    - pip

  run:
    - python                  {{ python }}
    - numpy                   >=1.21, !=1.24.0
    - scipy                   >=1.10.1
    - astropy
    - future

about:
  home: https://github.com/ratt-ru/eidos
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'edios - Primary beam modelling of radio astronomy antennas.'
  description: |
    Primary beam modelling of radio astronomy antennas.
  doc_url: https://github.com/i4Ds/eidos.git
  dev_url: https://github.com/i4Ds/eidos.git

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
