package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ EIDOS_VERSION }}

source:
  git_url: https://github.com/i4Ds/eidos.git
  git_rev: 323dedfcb063914e18ae939d758a4fa665a18ee2

build:
  noarch: python
  string: {{ EIDOS_VERSION }}

requirements:
  build:
    - python
    - pip
    - numpy {{ NUMPY_VERSION }}
    - scipy {{ SCIPY_VERSION }}
    - astropy
    - future

  host:
    - python
    - pip
    - numpy {{ NUMPY_VERSION }}
    - scipy {{ SCIPY_VERSION }}
    - astropy
    - future

  run:
    - python
    - pip
    - numpy {{ NUMPY_VERSION }}
    - scipy {{ SCIPY_VERSION }}
    - astropy
    - future

about:
  home: https://github.com/ratt-ru/eidos
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'edios - Primary beam modelling of radio astronomy antennas.'
  description: |
    Primary beam modelling of radio astronomy antennas.
  doc_url: https://github.com/i4Ds/eidos.git
  dev_url: https://github.com/i4Ds/eidos.git

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
