{% set pName = environ.get("PACKAGE_NAME")|lower %}
{% set pythonVersion = python|replace(".", "") %}
{% set fileName = pName + "-" + environ.get("FINUFFT_VERSION") + "-cp" + pythonVersion + "-cp" + pythonVersion + "-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" %}
{% if "nompi" == environ.get("MPI") %}
  {%  %}
{% else %}
  {%  %}
{% endif %}

package:
  name: {{ pName }}
  version: {{ FINUFFT_VERSION_ALT }}

source:
  url: "https://files.pythonhosted.org/packages/cp{{ pythonVersion }}/f/{{ pName }}/{{ fileName }}"

build:
  script_env:
    - FILE_NAME={{ fileName }}
    - FINUFFT_VERSION_ENV={{ FINUFFT_VERSION }}
  string: {{ FINUFFT_VERSION_ALT }}_{{ python }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - pip
    - python {{ python }}
    - make
    - cmake
    - numpy >=1.21, !=1.24.0
    - fftw =={{ FFTW3_VERSION_ALT }}
    
  host:
    - pip
    - python {{ python }}
    - numpy >=1.21, !=1.24.0
    - fftw =={{ FFTW3_VERSION_ALT }}

  run:
    - pip
    - python {{ python }}
    - numpy >=1.21, !=1.24.0
    - fftw =={{ FFTW3_VERSION_ALT }}

about:
  home: https://github.com/flatironinstitute/finufft
  license: MIT License or MIT
  license_family: MIT
  summary: 'Nonuniform Fast Fourier Transform library'
  description: |
   Flatiron Institute Nonuniform Fast Fourier Transform library: FINUFFT
  doc_url: https://github.com/epfl-radio-astro/bipp#readme
  dev_url: https://github.com/epfl-radio-astro/bipp

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
