{% set pName = environ.get("PACKAGE_NAME")|lower %}
{% set pythonVersion = python|replace(".", "") %}
{% set fileName = pName + "-" + environ.get("FINUFFT_VERSION") + "-cp" + pythonVersion + "-cp" + pythonVersion + "-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" %}

package:
  name: {{ pName }}
  version: {{ FINUFFT_VERSION_ALT }}

source:
  url: "https://files.pythonhosted.org/packages/cp{{ pythonVersion }}/f/{{ pName }}/{{ fileName }}"

build:
  script_env:
    - FILE_NAME={{ fileName }}
    - FINUFFT_VERSION_ENV={{ FINUFFT_VERSION }}
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - python
    - make
    - cmake
    - numpy
    - fftw
    
  host:
    - python          {{ python }}
    - pip
    - numpy
    - fftw            =={{ FFTW3_VERSION_ALT }}

  run:
    - python          {{ python }}
    - {{ pin_compatible('numpy') }}
    - fftw            =={{ FFTW3_VERSION_ALT }}

about:
  home: https://github.com/flatironinstitute/finufft
  license: MIT License or MIT
  license_family: MIT
  summary: 'Nonuniform Fast Fourier Transform library'
  description: |
   Flatiron Institute Nonuniform Fast Fourier Transform library: FINUFFT
  doc_url: https://github.com/epfl-radio-astro/bipp#readme
  dev_url: https://github.com/epfl-radio-astro/bipp

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
