{% set pName = {{ PACKAGE_NAME|lower }} %}
{% set pythonVersion = {{ python|replace(".", "") }} %}
{% set fileName = "{{ pName }}-{{ FINUFFT_VERSION }}-cp{{ pythonVersion }}-cp{{ pythonVersion }}-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" %}

package:
  name: {{ pName }}
  version: {{ FINUFFT_VERSION_ALT }}

source:
  url: "https://files.pythonhosted.org/packages/cp{{ pythonVersion }}/f/{{ pName }}/{{ fileName }}"

build:
  string: {{ FINUFFT_VERSION_ALT }}

requirements:
  build:
    script_env
      -FILE_NAME = {{ fileName }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - pip
    - python {{ python }}
    - make
    - cmake
    
  host:
    - pip
    - python {{ python }}

  run:
    - pip
    - python {{ python }}

about:
  home: https://github.com/flatironinstitute/finufft
  license: MIT License or MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Nonuniform Fast Fourier Transform library'
  description: |
   Flatiron Institute Nonuniform Fast Fourier Transform library: FINUFFT
  doc_url: https://github.com/epfl-radio-astro/bipp#readme
  dev_url: https://github.com/epfl-radio-astro/bipp

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
