package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PYBDSF_VERSION_ALT }}

source:
  git_url: https://github.com/i4Ds/PyBDSF.git

build:
  string: {{ PYBDSF_VERSION_ALT }}_{{ python }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - cmake         >=3.18
    - python        {{ python }}
    - pip
    - numpy         >=1.21
    - boost         {{ BOOST_VERSION_ALT }}.*
    - setuptools    >=68
    - scikit-build  >=0.13
    
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - cmake         >=3.18
    - python        {{ python }}
    - pip
    - numpy         >=1.21
    - boost         {{ BOOST_VERSION_ALT }}.*
    - setuptools     >=68
    - scikit-build   >=0.13
    
  run:
    - python        {{ python }}
    - boost         {{ BOOST_VERSION_ALT }}.*
    - astropy
    - numpy         >=1.21
    - scipy         >=1.10.1
    - matplotlib
    - ipython

about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
