package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PYBDSF_VERSION }}

source:
  url: https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ PYBDSF_VERSION }}.tar.gz

build:
  string: {{ PYBDSF_VERSION }}_{{ python }}
  script_env:
    - PYBDSF_VERSION
    - DEV_BUILD

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - python {{ python }}
    - pip
    - numpy {{ NUMPY_VERSION }}.*
    - boost {{ BOOST_VERSION }}.*
    - setuptools ==59.8.0
    
  host:
    - python {{ python }}
    - numpy {{ NUMPY_VERSION }}.*
    - boost {{ BOOST_VERSION }}.*
    - astropy
    - matplotlib
    - setuptools ==59.8.0
    
  run:
    - python {{ python }}
    - boost {{ BOOST_VERSION }}.*
    - astropy
    - numpy {{ NUMPY_VERSION }}.*
    - scipy {{ SCIPY_VERSION }}
    - matplotlib
    - ipython

about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
