package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PYBDSF_VERSION_ALT }}

source:
  url: https://pypi.io/packages/source/b/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ PYBDSF_VERSION }}.tar.gz

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - python
    - cmake                   >=3.18
    - numpy
    - ninja
    
  host:
    - python                  {{ python }}
    - numpy
    - pip
    - setuptools              <=65.6
    - libboost-python-devel   >=1.74
    - ninja
    - scikit-build            >=0.13
    - wheel
    
  run:
    - python                  {{ python }}
    - astropy
    - {{ pin_compatible('numpy') }}
    - scipy                   >=1.10.1
    - ipython

about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
