package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ SEQFILE_VERSION }}"

source:
  url: "https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ SEQFILE_VERSION }}.tar.gz"

build:
  noarch: python
  string: {{ SEQFILE_VERSION }}
  script_env:
    - SEQFILE_VERSION
    - DEV_BUILD
#  entry_points:
#    - seqfile = seqfile.seqfile:_run

requirements:
  build:
    - python
    - pip

  host:
    - natsort >=3.5.6
    - nose >=1.0
    - pep8 >=1.6.2
    - pip
    - python

  run:
    - natsort >=3.5.6
    - nose >=1.0
    - pep8 >=1.6.2
    - pip
    - python

about:
  home: "https://github.com/musically-ut/seqfile"
  license: MIT License or MIT
  license_family: MIT
  license_file: 
  summary: "Find the next file in a sequence of files in a thread-safe way."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
