{% set name = "ska-sdp-func" %}
{% set fileName = name|replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ SKA_SDP_FUNC_VERSION }}

source:
  git_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func.git

build:
  number: 0
  
requirements:
  build:
    - libgcc-ng=11.3 # will fail with compiler version above
    - cmake
    - make
    - python {{ python }}
    - pip 

  host:
    - libgcc-ng=11.3 # will fail with compiler version above
    - cmake
    - make
    - python {{ python }}
    - pip
    
  run:
    - python {{ python }}
    - pip
    - numpy {{ NUMPY_VERSION }}.*

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-func/
  license: BSD
  license_file: LICENSE
  summary: 'SKA SDP Processing Functions'
  description: |
   SKA SDP Functions
  doc_url: https://developer.skao.int/projects/ska-sdp-func/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch 
    