package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_FUNC_VERSION_ALT }}

source:
  git_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func.git
  git_tag: {{ SKA_SDP_FUNC_VERSION }}-testing

build:
  number: {{ BUILD_NUMBER }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ BUILD_NUMBER }}
  
requirements:
  build:
    - libgcc-ng=11.3 # will fail with compiler version above
    - cmake
    - make
    - python  {{ python }}
    - pip
    - numpy

  host:
    - python  {{ python }}
    - numpy
    
  run:
    - python  {{ python }}
    - {{ pin_compatible('numpy') }}

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-func/
  license: BSD
  license_file: LICENSE
  summary: 'SKA SDP Processing Functions'
  description: |
   SKA SDP Functions
  doc_url: https://developer.skao.int/projects/ska-sdp-func/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
    