package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ ARATMOSPY_VERSION_ALT }}"

source:
  git_url: "https://github.com/i4Ds/ARatmospy"
  git_rev: "e9210243d828fba04ab8dc00dd84af8d8572160c"

build:
  noarch: python
  number: {{ BUILD_NUMBER }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ BUILD_NUMBER }}

requirements:
  build:
    - python                  {{ python }}
    - pip

  host:
    - python                  {{ python }}
    - pip

  run:
    - astropy
    - matplotlib
    - numpy                   >=1.21, !=1.24.0
    - pyfftw
    - scipy                   >=1.9
    - pip
    - python                  {{ python }}

about:
  home: "https://github.com/i4Ds/ARatmospy"
  license: MIT License or MIT
  license_family: MIT
  license_file: 
  summary: "Python version of autoregressive atmosphere generator."
  doc_url: "https://github.com/i4Ds/ARatmospy"
  dev_url: "https://github.com/i4Ds/ARatmospy"

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
