package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ ARATMOSPY_VERSION_ALT }}"

source:
  git_url: "https://github.com/i4Ds/ARatmospy"
  git_rev: "4e3b8867ec7926cac05a39f2492b0dcdbbf4e46b"

build:
  noarch: python
  string: {{ ARATMOSPY_VERSION_ALT }}

requirements:
  build:
    - python
    - pip

  host:
    - astropy
    - matplotlib
    - numpy
    - pyfftw
    - scipy
    - pip
    - python

  run:
    - astropy
    - matplotlib
    - numpy
    - pyfftw
    - scipy
    - pip
    - python

about:
  home: "https://github.com/i4Ds/ARatmospy"
  license: MIT License or MIT
  license_family: MIT
  license_file: 
  summary: "Python version of autoregressive atmosphere generator."
  doc_url: "https://github.com/i4Ds/ARatmospy"
  dev_url: "https://github.com/i4Ds/ARatmospy"

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
