{% set name = "BDSF" %}

package:
  name: {{ name|lower }}
  version: {{ PY_BDSF_VERSION }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - python {{ python }}
    - pip
    - numpy {{ numpy }}
    - boost {{ boost }}
    
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - boost {{ boost }}
    - astropy
    - matplotlib
    
  run:
    - python {{ python }}
    - boost {{ boost }}
    - astropy
    - numpy {{ numpy }}
    - scipy
    - matplotlib
    - ipython

about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
