{% set uNameAndVers = PACKAGE_NAME|replace("-", "_") + "-" + SKA_SDP_FUNC_PY_VERSION %} # naming convention needs this

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_FUNC_PY_VERSION }}

source:
   url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_FUNC_PY_VERSION }}/{{ uNameAndVers }}.tar.gz

build:
  noarch: python
  number: 0
  script_env:
   - INTERNAL_FOLDER_NAME={{ uNameAndVers }}
  
requirements:
  build:
    - python                >=3.9
    - pip
    - poetry-core
    - astroplan             >=0.8
    - ducc0                 >=0.27.0,       <0.28
    - photutils             >=1.5
    - ska-sdp-datamodels    {{ SKA_SDP_DTMDL_VERSION }}.*
    - ska-sdp-func          {{ SKA_SDP_FUNC_VERSION }}.*

  host:
    - python                >=3.9
    - pip
    - poetry-core
    - astroplan             >=0.8
    - ducc0                 >=0.27.0,       <0.28
    - photutils             >=1.5
    - ska-sdp-datamodels    {{ SKA_SDP_DTMDL_VERSION }}.*
    - ska-sdp-func          {{ SKA_SDP_FUNC_VERSION }}.*
    
  run:
    - python                >=3.9
    - pip
    - astroplan             >=0.8
    - astropy               >=5.1
    - ducc0                 >=0.27.0,       <0.28
    - numpy                 {{ NUMPY_VERSION }}.*
    - photutils             >=1.5
    - scipy                 >=1.9.3
    - ska-sdp-datamodels    {{ SKA_SDP_DTMDL_VERSION }}.*
    - ska-sdp-func          {{ SKA_SDP_FUNC_VERSION }}.*
    - xarray                >=2022.11.0  

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python/
  license: Apache 2.0
  license_file: {{ uNameAndVers }}/LICENSE
  summary: 'SKA SDP Python Processing Functions'
  description: |
   SKA SDP Function Python Wrapper
  doc_url: https://developer.skao.int/projects/ska-sdp-func-python/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python

extra:
  recipe-maintainers:
    - filip.schramka@fhnw.ch
