name: MontagePy 

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false

jobs:

  Bluebild :
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: MontagePy
      packageVersion: $MONTAGEPY_VERSION
      packageVersionName: MONTAGEPY_VERSION
      customPath: montagepy/.
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      isNative: true
    secrets: inherit
