name: PyBDSF

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
    secrets:
      passedSecret: ${{ secrets.ANACONDA_SECRET }}
        
  workflow_call:
    inputs:
      label:
        type: string
        default: "main"
        required: true
    secrets:
      passedSecret:
        required: true

jobs:

  PyBDSF:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: bdsf
      packageVersion: $PYBDSF_VERSION
      customPath: pybdsf/.
      pythonCall: import bdsf.functions as func
      label: ${{ inputs.label }}
      isNative: true
    secrets:
      condaSecret: ${{ secrets.passedSecret }}
