name: PyBDSF

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true

jobs:

  PyBDSF:
    uses: ./.github/workflows/build_base.yml
    with:
      recipe_path: pybdsf/conda/.
      package_name: bdsf
      package_version: $PYBDSF_VERSION
      python_call: import bdsf.functions as func
      label: ${{ inputs.label }}
      isNative: true
    secrets:
      condaSecret: ${{ secrets.ANACONDA_SECRET }}

