name: Oskar Python Wrapper

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      fromTree:
        type: boolean
        required: false
        default: false

jobs:

  OskarPy:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: oskarpy
      packageVersion: $OSKAR_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      devDeps: "OSKAR_VERSION"
      fromTree: ${{ inputs.fromTree }}
      pythonCall: import oskar
      customPath: oskar-py/.
      isNative: true
    secrets: inherit
