name: FINUFFT

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true

jobs:

  FINUFFT:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: finufft
      packageVersion: $FINUFFT_VERSION
      packageVersionName: FINUFFT_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      buildNumber: ${{ inputs.buildNumber }}
      isNative: true
      useCuda: true
    secrets: inherit
