name: Karabo Feedstock Workflow for the SKA SDP Func

on:
  workflow_dispatch:

jobs:

  SKA_SDP_Func:
    uses: ./.github/workflows/build_base.yml
    with:
      recipe_path: ska-sdp-func/conda/.
      upload_filePath: /usr/share/miniconda/conda-bld/noarch/ska-sdp-func-*.tar.bz2
      package_name: ska-sdp-func
      package_version: $SKA_SDP_FUNC_VERSION
      python_call: ska_sdp_func
