name: PFFT

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
      devDeps:
        type: string
        required: false
        default: "FFTW3_VERSION"
      buildNumber:
        type: string
        required: false
        default: "0"
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      devDeps:
        type: string
        required: false
        default: "FFTW3_VERSION"
      buildNumber:
        type: string
        required: true

jobs:

  PFFT:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: pfft
      packageVersion: $PFFT_VERSION
      packageVersionName: PFFT_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      buildNumber: ${{ inputs.buildNumber }}
      devDeps: ${{ inputs.devDeps }}
      isNative: true
    secrets: inherit
