name: Rascil

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true

jobs:

  Rascil:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: rascil
      packageVersion: $RASCIL_VERSION
      pythonCall: from rascil.apps.rascil_image_check import cli_parser, image_check
      label: ${{ inputs.label }}
    secrets:
      condaSecret: ${{ secrets.ANACONDA_SECRET }}
