name: PyBDSF

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true

jobs:

  PyBDSF:
    uses: ./.github/workflows/build_base.yml
    with:
      recipe_path: pybdsf/conda/.
      package_name: pybdsf
      package_version: $PY_BDSF_VERSION
      python_call: import bdsm.functions as func
      label: ${{ inputs.label }}
    secrets:
      condaSecret: ${{ secrets.ANACONDA_SECRET }}

