name: SKA SDP Datamodel

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true

jobs:

  SKA_SDP_Datamodel:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: ska-sdp-datamodels
      packageVersion: $SKA_SDP_DTMDL_VERSION
      pythonCall: from ska_sdp_datamodels import *
    secrets:
      condaSecret: ${{ secrets.ANACONDA_SECRET }}
