name: Build Oskar with dependency tree

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
jobs:

  OskarNative:
    uses: ./.github/workflows/build_oskar.yml
    with:
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
    secrets: inherit

  OskarPythonWrapper:
    needs: OskarNative
    uses: ./.github/workflows/build_oskar_py.yml
    with:
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
    secrets: inherit
