name: SKA Gridder Nifty Cuda

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true

jobs:

  SKA_Gridder_Nifty_Cuda:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: ska-gridder-nifty-cuda
      packageVersion: $SKA_GRDR_NFTY_CU_VERSION
      packageVersionName: SKA_GRDR_NFTY_CU_VERSION
      useCuda: true
      isNative: true
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      buildNumber: ${{ inputs.buildNumber }}
      skipTest: true
    secrets: inherit
