name: Karabo Feedstock Workflow

env:
  SKA_SDP_DTMDL_VERSION: 0.1.2
  VERSION: 0.7.0
  #VERSION: 0.7.dev0
  LABEL: main
  #LABEL: dev

on:
  workflow_dispatch:

jobs:
  buildAndUpload_SKA_SDP_Datamodel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/
          conda build -c i4ds -c conda-forge ./ska-sdp-datamodels/.
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/noarch/ska-sdp-datamodels-*.tar.bz2 --label $LABEL --force

  test_SKA_SDP_Datamodel:
    needs: buildAndUpload_SKA_SDP_Datamodel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Mamba Solver
        run: |
          conda update -y -n base conda
          conda install -y -n base conda-libmamba-solver
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda create -y -n testpy39 python=3.9
          conda activate testpy39
          conda install -y -c "i4ds/label/$LABEL" -c i4ds -c conda-forge ska_sdp_datamodels="$SKA_SDP_DTMDL_VERSION" --experimental-solver=libmamba
          python -c "import ska_sdp_datamodels"
          
          conda create -y -n testpy310 python=3.10
          conda activate testpy310
          conda install -y -c "i4ds/label/$LABEL" -c i4ds -c conda-forge ska_sdp_datamodels="$SKA_SDP_DTMDL_VERSION" --experimental-solver=libmamba
          python -c "import ska_sdp_datamodels"
          