name: PyBDSF

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true

jobs:

  PyBDSF:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: bdsf
      packageVersion: $PYBDSF_VERSION
      customPath: pybdsf/.
      pythonCall: import bdsf.functions as func
      label: ${{ inputs.label }}
      isNative: true
      py310rdy: false
    secrets: inherit
