name: Bluebild 

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
      devDeps:
        type: string
        required: false
        default: "FINUFFT_VERSION"
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      devDeps:
        type: string
        required: false
        default: "FINUFFT_VERSION"

jobs:

  Bluebild :
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: bluebild
      packageVersion: $BLUEBILD_VERSION
      packageVersionName: BLUEBILD_VERSION
      customPath: bipp/.
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      isNative: true
      useCuda: true
    secrets: inherit
