name: Eidos

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false

jobs:

  eidos:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: eidos
      packageVersion: $EIDOS_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      pythonCall: import eidos
    secrets: inherit
