name: Rascil

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      fromTree:
        type: boolean
        required: false
        default: false

jobs:

  Rascil:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: rascil
      packageVersion: $RASCIL_VERSION
      pythonCall: from rascil.apps.rascil_image_check import cli_parser, image_check
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      devDeps: "PYBDSF_VERSION, SKA_SDP_DTMDL_VERSION, SKA_SDP_FUNC_PY_VERSION, SKA_SDP_FUNC_VERSION"
    secrets: inherit
