name: Oskar Python Wrapper

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true

jobs:

  OskarPy:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: oskarpy
      packageVersion: $OSKAR_VERSION
      label: ${{ inputs.label }}
      pythonCall: import oskar
      customPath: oskar-py/.
      isNative: true
    secrets: inherit
