name: Oskar

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false

jobs:

  Oskar:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: oskar
      packageVersion: $OSKAR_VERSION
      packageVersionName: OSKAR_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      useCuda: true
      isNative: true
    secrets: inherit
