name: Build Base

env:
  # Native Global Libs
  BOOST_VERSION: 1.74 # casacore<--python-casacore<--rascil<--karabo needs boost 1.74
  NUMPY_VERSION: 1.22 # pybdsf does not work with higher versions yet

  # Pinocchio Line
  #PINOCCHIO_VERSION: 
  #PPFT_VERSION:
  FFTW3_VERSION: 3.3.10
  
  # Rascil Line
  PYBDSF_VERSION: 1.10.2
  RASCIL_VERSION: 1.0.0
  SKA_SDP_DTMDL_VERSION: 0.1.3
  SKA_SDP_FUNC_PY_VERSION: 0.1.4
  SKA_SDP_FUNC_VERSION: 0.0.6

on:
  workflow_call:
    inputs:
      recipe_path:
        required: true
        type: string
      package_name:
        required: true
        type: string
      package_version:
        required: true
        type: string
      python_call:
        required: false
        default: ""
        type: string
      label:
        required: false
        default: "main"
        type: string
      useCuda:
        required: false
        default: false
        type: boolean
      arch:
        required: false
        default: "noarch"
        type: string
      py310rdy:
        required: false
        default: true
        type: boolean
        
    secrets:
      condaSecret:
        required: true

jobs:   
  build_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Cuda Toolkit => ${{ inputs.useCuda }}
        if: ${{ inputs.useCuda }}
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      - name: Install Conda-Build and create target
        run: |
          conda install conda-build
          conda build -c i4ds/label/${{ inputs.label }} -c i4ds -c conda-forge ${{ inputs.recipe_path }}
      - name: Install and publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          conda install anaconda-client
          anaconda -t ${{ secrets.condaSecret }} upload /usr/share/miniconda/conda-bld/${{ inputs.arch }}/${{ inputs.package_name }}*.tar.bz2 --label ${{ inputs.label }} --force


  test_base:
    needs: build_base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Mamba Solver
        run: |
          #conda update -y -n base conda # conda update breaks libmamba currently
          conda install -y -n base conda-libmamba-solver
      - name: Install Package and test with Python 3.9
        shell: bash -l {0}
        run: |
          conda create -y -n testpy39 python=3.9
          conda activate testpy39
          conda install -y -c i4ds/label/${{ inputs.label }} -c i4ds -c conda-forge ${{ inputs.package_name }}="${{ inputs.package_version }}" --experimental-solver=libmamba
          python -c "${{ inputs.python_call }}"
      - name: Install Package and test with Python 3.10 => ${{ inputs.py310rdy }}
        if: ${{ inputs.py310rdy }}
        shell: bash -l {0}
        run: |
          conda create -y -n testpy310 python=3.10
          conda activate testpy310
          conda install -y -c i4ds/label/${{ inputs.label }} -c i4ds -c conda-forge ${{ inputs.package_name }}="${{ inputs.package_version }}" --experimental-solver=libmamba
          python -c "${{ inputs.python_call }}"
