name: SKA SDP Func Python Wrapper

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true

jobs:

  SKA_SDP_Func_Python_Wrapper:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: ska-sdp-func-python
      packageVersion: $SKA_SDP_FUNC_PY_VERSION
      pythonCall: from ska_sdp_func_python import *
      label: ${{ inputs.label }}
    secrets: inherit
