name: FFTW3

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
    secrets:
      passedSecret: ${{ secrets.ANACONDA_SECRET }}
        
  workflow_call:
    inputs:
      label:
        type: string
        default: "main"
        required: true
    secrets:
      passedSecret:
        required: true

jobs:

  FFTW3:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: fftw3
      packageVersion: $FFTW3_VERSION
      label: ${{ inputs.label }}
      isNative: true
    secrets:
      condaSecret: ${{ secrets.passedSecret }}