name: Eidos

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
        
  workflow_call:
    inputs:
      label:
        type: string
        required: true

jobs:

  eidos:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: eidos
      packageVersion: $EIDOS_VERSION
      label: ${{ inputs.label }}
      pythonCall: import eidos
    secrets: inherit
